### ISSUE TITLE
UnboundLocalError: local variable 'status' referenced before assignment

### ISSUE THREAD

**Issue by rpanev** [bgdnlp/pyzlack#2]
Hello,

i use zabbix 3 and 4, at 3 it works perfectly but at 4 i have the following error:

`Traceback (most recent call last):
File "/usr/lib/zabbix/alertscripts/pyzlack", line 266, in <module>
main()
File "/usr/lib/zabbix/alertscripts/pyzlack", line 253, in main
enrich_message(args.subject, args.body)
File "/usr/lib/zabbix/alertscripts/pyzlack", line 168, in enrich_message
if status == 'OK' or subject[0:3] == 'OK:':
UnboundLocalError: local variable 'status' referenced before assignment`

**Comment by bgdnlp** [comment]
It's looking for {TRIGGER.STATUS}, which should be part of the alert message. I'm guessing it's missing from your alert?

I should add a condition to check for that. Meanwhile, adding the status to the message should fix it.
